### ISSUE TITLE
Continued Header

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/bread#10]
somewhere in between bread 1.0 and bread 1.1.0, I have seemed to have lost the continued day header. It doesn't seem to be a problem of  decreasing my Page Height Adjust either as i have tried this. with the exact same json export on bread 1.0 i get may continued day headers but on all subsequent versions i don't. this also only applies to Weekday+Area, Weekday+City,  and Weekday+County. all other group meetings by the continued headers come up fine. was trying to figure out, maybe somewhere around line 984

**Comment by radius314** [comment]
investigating

**Comment by radius314** [comment]
found the bug and patched it

**Comment by radius314** [comment]
cut in 1.2.1, please test

**Comment by pjaudiomv** [comment]
works great now, thanks!
