### ISSUE TITLE
images not rendering

### ISSUE THREAD

**Issue by radius314** [radius314/bread#13]
Might be a regression.  Does not happen for existing schedules, but only new ones.

![https___mariettana_org__current-meeting-list_1](https://user-images.githubusercontent.com/1850811/38318361-20cf5118-37fd-11e8-86c0-09e74f7f1b91.png)

**Comment by radius314** [comment]
this issue occurs on the settings page.  

there is a separate issue that I faced with running in docker.  the image showed up fine on the settings page, but the rendered PDF have the red X

**Comment by radius314** [comment]
released, needs additional verification.

**Comment by djraptor** [comment]
We are now having this happen to ours in the FreeStateRegion. What's the fix so we can utilize images and QRCodes for newer meeting lists?

**Comment by jbraswell** [comment]
Out of curiosity, what is your web host? Is it SiteGround?

**Comment by djraptor** [comment]
Yes it is. The images are showing up on the older lists, just not on any newer ones we made.

**Comment by spiritualtheory** [comment]
Which solution did you try? Editing the functions.php file or the config file in mpdf?
