### ISSUE TITLE
Fonts 1.4.0

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/bread#15]
It would be nice if bread could include a couple standard true type fonts courier, arial, times. as natively mpdf uses weird fonts deja-vu, etc. This can be a problem with printers as they don't have these fonts. In previous bread versions using the older version of mpdf, this was easily achievable by dumping these fonts int he ttfonts directory and editing the config_fonts.php file. Now fonts can be dumped in a directory but have to be added in the script itself   https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html

**Comment by radius314** [comment]
This is a bug that affects a beta version.

**Comment by radius314** [comment]
Can you clarify what the defect is?  I'm less interested in how it used to function, and more interested in the ideal.  Also not a fan of having people upload fonts to the plugin directory.

**Comment by pjaudiomv** [comment]
Yes. I also agree not looking for a function where people upload things to plugin directory. Ideally bread would include some real true type fonts and not generic ones (like arial, times, helvetica, whatever the top three or four fonts. Printers (actual print shops) have trouble using these weird fonts. as they often may need to open the pdf in quark, or in design to use with their printers.

**Comment by radius314** [comment]
Sorry that statement seems conflicting to me.  Arial, Times, and Courier are very standard fonts.

**Comment by pjaudiomv** [comment]
sorry should of read that before posting. bread would include Arial, Times, and Courier. Currently the fonts that render to the pdf are deja-vu and some other ones that are similar to the standard fonts but arent.

**Comment by radius314** [comment]
I think the issue is the inability to set a "default" font.  Those fonts are available in each editor window, but the rest are not controllable.

**Comment by pjaudiomv** [comment]
yes they are available in the editor window but when it actually renders it becomes DejaVuSansCondensed

**Comment by radius314** [comment]
That is not true.  I was able to change a text block to Courier.  Keep in mind that you have to highlight the text first and then change it on the dropdown as it's essentially doing HTML formatting behind the scenes.

**Comment by pjaudiomv** [comment]
take https://ncregion-na.org/?current-meeting-list=1 for example the fonts used in that pdf are 
DejaVuSansCondensed
DejaVuSansCondensed-Bold
DejaVuSansCondensed-Oblique

**Comment by radius314** [comment]
Yes it's the default if you don't change a block of text.

**Comment by pjaudiomv** [comment]
yes even if I do change the block of txt to say Times it doesnt render as a times font, even if I go into txt mode check to make sure its definitley set to times it doesnt do it. the fonts look different on the pdf bot the actual font printed on the pdf isnt times

**Comment by radius314** [comment]
<img width="1580" alt="localhost_8080__current-meeting-list_1" src="https://user-images.githubusercontent.com/1850811/40213502-ceba0e42-5a23-11e8-8b1f-4ec0e2dbfc2b.png">

**Comment by radius314** [comment]
<img width="790" alt="meeting_list_ _admin_ _wordpress" src="https://user-images.githubusercontent.com/1850811/40213518-e0cf9d40-5a23-11e8-811e-987a099f80e8.png">

**Comment by radius314** [comment]
<img width="707" alt="meeting_list_ _admin_ _wordpress" src="https://user-images.githubusercontent.com/1850811/40213537-f9bc07d0-5a23-11e8-9fc1-b7a306e25bfa.png">

**Comment by pjaudiomv** [comment]
yes now download the generated pdf and open it in say illustrator, in design or quark and what font shows up

**Comment by radius314** [comment]
I don't have those programs.

**Comment by pjaudiomv** [comment]
![breadfont](https://user-images.githubusercontent.com/34245618/40213644-79c6c834-5a24-11e8-89fb-b1b69b1c8c06.png)

**Comment by pjaudiomv** [comment]
if you open the pdf in a txt editor you can also see this.

**Comment by pjaudiomv** [comment]
![dejavu](https://user-images.githubusercontent.com/34245618/40213773-3df9f398-5a25-11e8-86d5-78ef411e22c5.png)

**Comment by radius314** [comment]
Ok the issue is clear to me now.

**Comment by pjaudiomv** [comment]
cool im sorry for not explaining it well, felt like a abbot and costello skit for a second there.

**Comment by pjaudiomv** [comment]
everything looks great, and most service bodies probably dont have problems as they print there own pdfs on laser printers, or just print the pdfs at kinkos or staples or whatever, but print shops who use big high end printers sometimes need to tweak things and it'd be nice to have the actual fonts being used.

**Comment by pjaudiomv** [comment]
this is from a pdf I generated from current stable version and just dropped the times new roman font in the ttfonts mpdf directory and added the font data in config_fonts.php
![times](https://user-images.githubusercontent.com/34245618/40214066-be5f11de-5a26-11e8-96be-1de58115fd89.png)

**Comment by radius314** [comment]
Pushed https://github.com/radius314/bread/commit/9e526a950b600233ae57751fefd4b36f6c91eaae

**Comment by radius314** [comment]
Probably could open up more fonts in the editor view.

**Comment by pjaudiomv** [comment]
this isnt working still, i played with it a little at work but then i had to actually work. I got it to work by adding the fontdata array $this->mpdf->fontdata = array(.....all the fonts data. but theres got to be something im missing to make it simplier, as it said in mpdf 7.1 it is much simplier

**Comment by radius314** [comment]
Can you define "not working".  I got it to work on my end.

**Comment by radius314** [comment]
<img width="600" alt="document_properties" src="https://user-images.githubusercontent.com/1850811/40260854-fcbc8c0a-5aca-11e8-96fb-72ededc4765f.png">

**Comment by pjaudiomv** [comment]
ah I see you do, I'm gonna re pull and update and try again then.

**Comment by radius314** [comment]
One deficiency of the older versions is the ability to change the “default”
font.  How did you deal with this prior?

**Comment by pjaudiomv** [comment]
I tricked mpdf into thinking the default font was another in config_fonts.php as well as uploading the fonts into the font directory.

$this->fontdata = array(
	"dejavusanscondensed" => array(
		'R' => "TimesNewRoman.ttf",
		'B' => "TimesNewRomanBold.ttf",
		'I' => "TimesNewRomanItalic.ttf",
		'BI' => "TimesNewRomanBoldItalic.ttf",
		'useOTL' => 0xFF,
		'useKashida' => 75,
	),

**Comment by pjaudiomv** [comment]
so after just testing
Courier worked fine
Arial renders as helvetica but who cares there basically the same font
and times is still rendering as DejaVuSansCondensed

**Comment by radius314** [comment]
Ok the issue in general and defect of the older versions is the inability
to control the global default font.  I would say this is critical in
addressing this feature.

**Comment by pjaudiomv** [comment]
ok cool, thanks so much for taking our time to look a that. im gonna keep playing with it for a bit if I make any headway ill  let you know.

**Comment by radius314** [comment]
All 3 fonts render fine for me.

**Comment by radius314** [comment]
Figured out how all these defaults are being controlled.  https://github.com/radius314/bread/blob/unstable/css/mpdfstyletables.css

**Comment by radius314** [comment]
Also the rest of the defaults are set here: https://github.com/radius314/bread/blob/521bf2dba9204fd0321b9905dfd7b63b5de59391/mpdf/vendor/mpdf/mpdf/src/Config/FontVariables.php

**Comment by pjaudiomv** [comment]
ah ha font variables, there's an order for different font families in which a font is used if none is specified too

**Comment by radius314** [comment]
Check out the latest changes.  There is a new option:

<img width="1448" alt="meeting_list_ _admin_ _wordpress" src="https://user-images.githubusercontent.com/1850811/40275601-6c18e772-5bc2-11e8-8635-016f55f7d738.png">
