### ISSUE TITLE
Possible Mozilla rendering issue

### ISSUE THREAD

**Issue by waltersaunders** [radius314/bread#16]
![bread 3](https://user-images.githubusercontent.com/39493694/40316489-5d106b1c-5cd3-11e8-9934-795a8ed4c4e7.png)

The potential issue only appears in Firefox, works fine in other browsers.

**Comment by radius314** [comment]
Can you try in a Private Window of Firefox?  This will simulate not loading up Add-Ons/Extensions.  I want to see if it's clashing with something you have custom.

**Comment by waltersaunders** [comment]
Here you go

    On Monday, May 21, 2018, 9:04:13 AM PDT, Danny Gershman <notifications@github.com> wrote:  
 
 
Can you try in a Private Window of Firefox? This will simulate not loading up Add-Ons/Extensions. I want to see if it's clashing with something you have custom.

**Comment by radius314** [comment]
Closing, user error
