### ISSUE TITLE
Version 1.51 Issue with PDF protection

### ISSUE THREAD

**Issue by sfrna** [radius314/bread#24]
Since this is the first time I have used Bread I can't say whether this issue was here before or not. I installed and activated Bread, read all the instructions, and got this using service body 20, 42 to make a South Florida Regional meeting list:

No Meetings Found
Or
Internet or Server Problem

https://bmlt.sezf.org/main_server

Debug Information
Protocol: https://
PHP Version: 7.1.20
Server Version: LiteSpeed

I decided to see what could possibly be causing this issue. Found the problem. It doesn't like me to add PDF protection. I use a pretty secure password like xxxxxxxxxx1234@1234. Tried a simple password and still no go. Turning off password protection fixes the problem.

I'm the one who asked Jack to put this in about 3 years ago as we had certain individuals editing our Area meeting list and then putting it out that it was our Area meeting list.

**Comment by sfrna** [comment]
I noticed that deselecting recursive automatically returned it to selected on save. :-/

What exactly does the recursive function do?

**Comment by radius314** [comment]
That’s definitely another bug.

**Comment by sfrna** [comment]
pjaudiomv, how did you get the meeting legend to show? Is there some secret shortcode? I want to put it on the front page.

**Comment by pjaudiomv** [comment]
no secret its in the shortcode dropdown of the editor for custom content that one is [format_codes_used_basic]

**Comment by radius314** [comment]
Recursive means if it’s a regional body selected and “recursive” is selected it will include all the service bodies that are a part of that service body.

**Comment by radius314** [comment]
Obviously the checkbox not functioning is an issue.  It may be contributing to this pdf protection bug or be separate altogether.  Will take a look shortly.

**Comment by sfrna** [comment]
I'm assuming it automatically selects it because I specified a region?

**Comment by radius314** [comment]
The default behavior has always be recursive.  This option was added to
have as an option.

**Comment by pjaudiomv** [comment]
the mpdf SetProtection options are being set before this code for half-page runs, so when the half-page trys to write to the file it fails (because its protected already) moving the protection down or putting some kind of stipulation on it would fix this.

**Comment by radius314** [comment]
will be pushed in bread 1.5.2

**Comment by radius314** [comment]
please verify this has been fixed

**Comment by radius314** [comment]
Can you raise the PHP log level and let us know the actual error?

**Comment by radius314** [comment]
Any followup on this?

**Comment by radius314** [comment]
Since we are on 1.6.2 now closing this.  Please re-open if still having an issue.
