### ISSUE TITLE
V 1.51 egg shaped graphic on front page

### ISSUE THREAD

**Issue by sfrna** [radius314/bread#25]
I put our SFR graphic on the front page and I get an egg-shaped graphic on the meeting list. How do I fix this?

https://sfrna.net/?current-meeting-list=1

**Comment by radius314** [comment]
Not seeing the same.

**Comment by sfrna** [comment]
On the link I just posted? Our logo I see in Bread is round.

**Comment by radius314** [comment]
Not connecting the dots here.  Can you post an image of what it’s supposed to look like versus what you are seeing?  This will help greatly.

**Comment by sfrna** [comment]
I think this problem is something from Jack's plugin. This link has an egg-shaped NA logo.
https://nameetinglist.org/florida-central-west-metro/?current-meeting-list=1

**Comment by pjaudiomv** [comment]
it seems that its resizing the image width, where it should maybe be proportionally resizing width and height. id be curious if manually resizing the image to be smaller and including it in the pdf would still produce this result.

**Comment by radius314** [comment]
Can you send your config file?

**Comment by sfrna** [comment]
I resized the pic and no change. I also set it up in the back end smaller with it being on the left and text on the right. When generating a meeting list I get the text below the pic.
https://sfrna.net/?current-meeting-list=1


[-meeting-list-settings-08-19-2018.zip](https://github.com/radius314/bread/files/2300125/-meeting-list-settings-08-19-2018.zip)

**Comment by radius314** [comment]
![notes](https://user-images.githubusercontent.com/1850811/44310982-99372d80-a3ad-11e8-97a7-8dd55536f08f.png)

**Comment by radius314** [comment]
@sfrna is this what you mean by eggy?  the image being stretched vertically?

**Comment by sfrna** [comment]
Yes

**Comment by radius314** [comment]
Yeah i noticed that too.

**Comment by pjaudiomv** [comment]
Not a fix but a way around this would be to use a table with two cells, image on left cell and txt on right cell

**Comment by radius314** [comment]
To add new BMLT formats, contact your BMLT administrator.

**Comment by radius314** [comment]
The image stretchiness bug will be fixed in bread 1.5.2

**Comment by radius314** [comment]
please verify this is fixed

**Comment by sfrna** [comment]
The image is correct now. Should I open threads on the other issues?

**Comment by radius314** [comment]
You can try.
