### ISSUE TITLE
Generated mtg list shows up in Yap folder

### ISSUE THREAD

**Issue by sfrna** [radius314/bread#28]
Why when I create a meeting list does it end up in our Yap folder. Any ideas what's going on or do I need to get the site checked for malware? This started back in February 2018. Happens every time I generate a meeting list. Seems weird that it goes into that particular folder! How can a WP app write to a PHP folder that hasn't anything to do with each other except the developer?

![bread yap mtg list](https://user-images.githubusercontent.com/39550875/44428941-ec52e100-a563-11e8-986e-39de2377dd0b.JPG)

**Comment by pjaudiomv** [comment]
May not hurt to do an export, deactivate the plugin, then delete it then reinstall and activate and import settings. This should only happen if the mpdf output settings are set to File, and I don't believe it is anywhere. As for the directory there going to there's a number of things it could be but not sure. I would think it would go to the root directory.

**Comment by sfrna** [comment]
I think I misspoke here as I think the screen shot I took was of the main html folder and I just had the Yap folder open. Checked the public_html folder and that's where they are at now.

Any way to automatically delete the previous meeting list after writing a new one. If someone wasn't specifically rummaging around in file mgr they might never see this.

**Comment by sfrna** [comment]
I just looked in the ECFA file manager and these pdf files aren't in their folder and they use Jack's plugin. This inclines me to believe this is a Bread issue.

Not sure why they even need to be written as it generates a meeting list on the fly. Each meeting list at https://sfrna.net/?current-meeting-list=1 shows the date it was created.

**Comment by pjaudiomv** [comment]
@radius314 
[half page temp](https://github.com/radius314/bread/blob/unstable/bmlt-meeting-list.php#L1240-L1290)
this is the only place this could be happening, the only thing i could think is maybe for some reason her permission arent right to unlink the file on L1287
[unlink](https://github.com/radius314/bread/blob/unstable/bmlt-meeting-list.php#L1287)

**Comment by pjaudiomv** [comment]
damn was kind of hoping that would display the lines inline :(

**Comment by radius314** [comment]
These lines of code come from the original plugin.  It's probably because you are getting a failure on the PDF protection that it's not getting to the point where it would be deleting them.

**Comment by sfrna** [comment]
What should the files have for permissions?

**Comment by radius314** [comment]
This is not a permissions issue.  It’s a side effect I believe of pdf
protection not working.

**Comment by radius314** [comment]
related to #24

**Comment by radius314** [comment]
Since we are on 1.6.2 now, closing this.  Please re-open if it's reoccurs.
