### ISSUE TITLE
half page layout not outputting correct size

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/bread#29]
when choosing half-fold as page size and booklet (11" x 8.5"), the width is correct at 11" (792pt) but the height is not its 7.76 inches (558.992 pts). the correct height should be 8.5 inches (612pts)
instead of setting the size in mm i would suggest just setting the format to Letter. this will most likely break #25 again. However i believe outputting the correct page sizes is more important.
this has to do in part to the fix for #25

**Comment by radius314** [comment]
released in 1.5.3
