### ISSUE TITLE
page numbering adds blank pages

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/bread#30]
when using half page lay out and [start_page_numbers], 2 extra blank pages are added. this seems like it could be a mPDF bug.  I tried doing something like the following right before output as a work around which would remove the blank pages but would also remove the last page. 

`
$rm_page = $this->mpdf->page - 1;
$this->mpdf->DeletePages($rm_page);
`

Ex. http://www.crna.org/?current-meeting-list=1

removing [start_page_numbers] removes blank pages

**Comment by pjaudiomv** [comment]
confirmed this is not a mPDF bug theres something else conflicting with it

**Comment by pjaudiomv** [comment]
this fixes it
https://github.com/radius314/bread/compare/unstable...pjaudiomv:pagenumbers

**Comment by pjaudiomv** [comment]
seem to be a problem with size and margins, and I don't know why it didn't like the string replace but it didnt.

**Comment by pjaudiomv** [comment]
this would fix #29 as well but break #25

**Comment by pjaudiomv** [comment]
NOPE many expletives, there is something weirder going on. it fixed it in that unique case but not for others. it seems to be a page size thing maybe the page size needs to be different than the sheet(document size) idk

**Comment by pjaudiomv** [comment]
its def sizing thing. this fixes it. ive tried it with various half page settings
https://github.com/radius314/bread/compare/unstable...pjaudiomv:unstable

**Comment by radius314** [comment]
released in 1.5.3
