### ISSUE TITLE
Version 1.6.2 Wordpress plugin fails to install

### ISSUE THREAD

**Issue by max-lancaster** [radius314/bread#37]
Getting the following error trying to install the bread wordpress plugin:

`Could not copy file. bread/mpdf/vendor/mpdf/mpdf/ttfonts/Sun-ExtA.ttf `

**Comment by pjaudiomv** [comment]
curious, are you installing this from the word press repository or uploading.

**Comment by max-lancaster** [comment]
I tried both ways and it failed several times but after several retries it finally did install successfully, persistence pays off!  So maybe we close this issue unless other people report similar problems.
