### ISSUE TITLE
"Meeting List" not appearing in Wordpress

### ISSUE THREAD

**Issue by Redguy1959** [radius314/bread#40]
PHP 7.0.32, Wordpress 4.9.8, Apache server, Bread 1.6.2

Plugin installed and activated but we don't see the Meeting List link to configure the plug in.

**Comment by radius314** [comment]
Anything showing up in PHP error log?

**Comment by Redguy1959** [comment]
Staying activated – no errors appear.

**Comment by radius314** [comment]
What about server logs?
What’s the OS?

**Comment by Redguy1959** [comment]
OS is Linux of some sort. I will check later for logs – have all day service commitments.

**Comment by Redguy1959** [comment]
Which server logs would be helpful?
  ----- Original Message -----

**Comment by radius314** [comment]
what OS distro you on?

**Comment by Redguy1959** [comment]
All they give me is this: 
      Kernel Version 3.10.0-693.17.1.2.ELK.el6.x86_64 


I will see if I can get SSH access.
  ----- Original Message -----

**Comment by radius314** [comment]
Ok that's the kernel version.  Is this a cpanel based host?  There should be error logs available somewhere.  Otherwise will if it's a modern debian-based distro log would typically be in /var/log/apache2/error.log.

**Comment by radius314** [comment]
Also, 1.7.3 is now available, have you tried against this version?

**Comment by Redguy1959** [comment]
Yes, we are on 1.7.3. Same issue, no Meeting List link. Where is it supposed to show? I've seen it but forget.
  ----- Original Message -----

**Comment by radius314** [comment]
![dashboard_ _nc_region_of_narcotics_anonymous_ _wordpress](https://user-images.githubusercontent.com/1850811/47673633-93b74a00-db8b-11e8-90a7-e3266c532a8d.png)

**Comment by Redguy1959** [comment]
It's definitely not anywhere to be found. Just making sure I wasn't missing something.
  ----- Original Message -----

**Comment by radius314** [comment]
Ok logs?  I think you are missing email replies.

What other plugins are you using?
Any JavaScript console errors ?

**Comment by Redguy1959** [comment]
I am not missing any email replies, I just didn't send any logs to you yet because I don't have them.
  ----- Original Message -----

**Comment by radius314** [comment]
What PHP version?

**Comment by Redguy1959** [comment]
In original post, 7.0.32
  ----- Original Message -----

**Comment by radius314** [comment]
What’s the Wordpress server url?

**Comment by Redguy1959** [comment]
www.cjasc.org 
  ----- Original Message -----

**Comment by radius314** [comment]
Do you have a plugin installed that adds additional permissions to the
admin menu?

**Comment by Redguy1959** [comment]
[cid:151455820@29102018-2B84]

[cid:151455820@29102018-2B8B]


________________________________

**Comment by Redguy1959** [comment]
Not as far as I know. Should we? Just sent screen shots of the PlugIns.

  ----- Original Message -----

**Comment by radius314** [comment]
Not seeing any screenshots.

**Comment by radius314** [comment]
Do you have the legacy BMLT Meeting List Generator Plugin installed?

**Comment by Redguy1959** [comment]
I will send them to your gmail - maybe they don;t come through on this platform.
  ----- Original Message -----

**Comment by Redguy1959** [comment]
No. I don't believe that was ever installed on this site.
  ----- Original Message -----

**Comment by radius314** [comment]
It's definitely installed and working.  It's generating a schedule.  http://cjasc.org/?current-meeting-list=1

Also, are you able to hit this URL once you are logged in?  Ihttp://cjasc.org/wp-admin/admin.php?page=bmlt-meeting-list.php

It looks like it was working at some point because you were able to somewhat configure it.  If so, what was the last known good working version?

**Comment by Redguy1959** [comment]
Yes, I am able to hit the configuration link when logged in.

Yes, we did have a version where the Meeting List link showed up. I have no idea what version that was, but it was not the latest and not the one right before it.
  ----- Original Message -----

**Comment by Redguy1959** [comment]
Is it possible for me to install some older version of the plugin?
  ----- Original Message -----

**Comment by pjaudiomv** [comment]
im late to the show here but have you tried deactivating it, deleting it and the re adding it. It must of been at least 1.5.3 because it looks like export query string isnt working and that is when that was disabled.

**Comment by Redguy1959** [comment]
Yes, already tried what you suggested.
  ----- Original Message -----

**Comment by radius314** [comment]
There is a dropdown on this page the should let you download and manually install older versions.

https://wordpress.org/plugins/bread/advanced/

**Comment by Redguy1959** [comment]
Tried 1.5.3 then 1.6.0 then 1.6.1. Still no link


----- Original Message -----

**Comment by pjaudiomv** [comment]
how about 1.5.2
https://downloads.wordpress.org/plugin/bread.1.5.2.zip

**Comment by Redguy1959** [comment]
I just found out if I deactivate the Secure Downloads plugin the Meeting List link appears where the Secure Downloads link used to be. If I reactivate Secure Downloads the Meeting List link is replaced by Secure Downloads.
  ----- Original Message -----

**Comment by radius314** [comment]
That plugin was actually my suspicion, but I didn’t say anything out loud.
I’ll look into see if I can figure out what’s clashing with that plugin.

**Comment by radius314** [comment]
Able to repro the issue with Secure Downloads plugin.

**Comment by radius314** [comment]
Patched in bread 1.7.4, please verify.

**Comment by Redguy1959** [comment]
It works! Confused me at first because Meeting List link was near the top of the page, then when I activated Secure Downloads the Meeting List link moved near the bottom, but that is fine.

Thanks!
  ----- Original Message -----

**Comment by radius314** [comment]
Yup the issue was that in prior versions of Wordpress, you *had* to include the sequence.  This caused many issues, so I WP 4.4 and greater the mechanism was changed to allow WP internally to manage that.  As a result, Wordpress will decide now where to insert that link.

**Comment by radius314** [comment]
Will make a formal announcement later today on FB group about this change.
