### ISSUE TITLE
[month_lower] showing up on front page at top right

### ISSUE THREAD

**Issue by californiasteve** [radius314/bread#50]
https://pdfnameetings.org/tejas-bluebonnet-region-esperanza-area/?current-meeting-list=1
Version 1.7.7

**Comment by californiasteve** [comment]
![image](https://user-images.githubusercontent.com/31661648/47859755-fd6a6a80-ddbc-11e8-818f-dd563c1f0c7b.png)

**Comment by radius314** [comment]
Not sure if it’s related but the year seems to be bunched at the bottom next to the meeting count.

**Comment by californiasteve** [comment]
I'm digging somemore. It's not happening other sites I have upgraded just this one.

**Comment by radius314** [comment]
I'm not able to repro.

**Comment by pjaudiomv** [comment]
Me neither I tried a few different ways, nothing crazy extensive. Curious weather downgrading would fix it or not.

**Comment by radius314** [comment]
Can you export the settings and attach them?

**Comment by californiasteve** [comment]
Found it, the meeting list person had added it to the end of the custom content. All better. Thanks Danny and patrick.
