### ISSUE TITLE
meetings by weekday and city with no city header

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/bread#7]
it would be nice to have an option to view meetings by weekday and city but not include the city header. this could be useful for regional meeting directories. this could be an additional drop down or checkbox option.  for now i commented out lines 997 and 1002 and it does what i need it to which is example b.

`$header .= "<p style='margin-top:1pt; padding-top:1pt; font-weight:bold;'>".$area_name."</p>";` 

example a current way: https://areas.nerna.org/nerna/?current-meeting-list=1
example b proposed option: https://wp.nerna.org/?current-meeting-list=1

i may take a crack at this seems like it could be within my skill set, but if you think you could do this easy enough go for it.

**Comment by radius314** [comment]
Seems like an interesting feature.  Something like "hide secondary grouping".  Some javascript to detect that Group By has 2 items.

**Comment by radius314** [comment]
```To get things going in your local environment.

docker-compose up

Get your wordpress installation going. Remember your admin password. Once it's up, login to admin and activate the BMLT meeting list plugin.

Now you can make edits to the bmlt-meeting-list.php file and it will instantly take effect.```

**Comment by pjaudiomv** [comment]
i gotta get this docker thing for my mac

**Comment by radius314** [comment]
Cool, let me know if you need a crash course in docker.

**Comment by radius314** [comment]
ref: https://github.com/radius314/bread/pull/8

**Comment by radius314** [comment]
this was release in bread 1.2.0
